package gov.nih.mipav.model.scripting.parameters;


import gov.nih.mipav.model.scripting.ParserException;


/**
 * A image placeholder variable parameter used in either the recording or execution of a script action. This type of
 * image parameter indicates that the image is not generated by other script actions; it must be specified externally by
 * whatever is running the script that this parameter is used in.
 */
public class ParameterExternalImage extends ParameterImage {

    // ~ Constructors
    // ---------------------------------------------------------------------------------------------------

    /**
     * Creates a new ParameterImage object.
     * 
     * @param paramLabel The label/name to give to this parameter.
     * 
     * @throws ParserException If there is a problem creating the parameter.
     */
    public ParameterExternalImage(final String paramLabel) throws ParserException {
        super(paramLabel, Parameter.PARAM_EXTERNAL_IMAGE);
    }

    /**
     * Creates a new ParameterExternalImage object.
     * 
     * @param paramLabel The label/name to give to this parameter.
     * @param paramTypeString The type of this parameter, in string form.
     * @param paramValueString The new parameter value.
     * 
     * @throws ParserException If there is a problem creating the parameter.
     */
    public ParameterExternalImage(final String paramLabel, final String paramTypeString, final String paramValueString)
            throws ParserException {
        super(paramLabel, paramTypeString, paramValueString);
    }

    /**
     * Creates a new ParameterExternalImage object.
     * 
     * @param paramLabel The label/name to give to this parameter.
     * @param paramType The type of this parameter (should be PARAM_EXTERNAL_IMAGE).
     * @param paramValueString The new parameter value.
     * 
     * @throws ParserException If there is a problem creating the parameter.
     */
    public ParameterExternalImage(final String paramLabel, final int paramType, final String paramValueString)
            throws ParserException {
        super(paramLabel, paramType, paramValueString);
    }
}
