package gov.nih.mipav.model.algorithms;

import gov.nih.mipav.model.structures.*;
import gov.nih.mipav.view.*;

import java.io.*;

public class AlgorithmNonMaxSuppts extends AlgorithmBase {
	/** 
	Non-maximal suppression for features/corners
    Non maxima suppression and thresholding for points generated by a feature
    or corner detector.

	Note: An issue with integer valued images is that if there are multiple pixels
	all with the same value within distance 2*radius of each other then they will
	all be marked as local maxima. 

	Copyright (c) 2003-2013 Peter Kovesi
	Centre for Exploration Targeting
	The University of Western Australia
	peter.kovesi at uwa edu au
	
	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, subject to the following conditions:
	 
	The above copyright notice and this permission notice shall be included in all
	copies or substantial portions of the Software.
	
	The Software is provided "as is", without warranty of any kind.

	September 2003  Original version
	August    2005  Subpixel localization and Octave compatibility
	January   2010  Fix for completely horizontal and vertical lines (by Thomas Stehle,
                 RWTH Aachen University) 
	January   2011  Warning given if no maxima found
	*/
	
	private int radius;
	private double threshold;
	private int row[];
	private int column[];
	private double rsubp[] = null;
	private double csubp[] = null;
	
	/**
	 * 
	 * @param destImg  Optional image.  If this is supplied, the thresholded corners are overlayed on
	 *                 this image.  This can be useful for parameter tuning
	 * @param srcImg   Corner strength image
	 * @param radius   Radius of the region considered in non-maximal suppression.
	 *                 Typical values to use might be 1-3 pixels.
	 * @param threshold
	 * @param row row coordinates of corner points
	 * @param column column coordinates
	 */
	public AlgorithmNonMaxSuppts(ModelImage destImg, ModelImage srcImg, int radius, double threshold,
			                     int[] row, int[] column) {
		super(destImg, srcImg);	
		this.radius = radius;
		this.threshold = threshold;
		this.row = row;
		this.column = column;
	}
	
	/**
	 * 
	 * @param destImg  Optional image.  If this is supplied, the thresholded corners are overlayed on
	 *                 this image.  This can be useful for parameter tuning
	 * @param srcImg   Corner strength image
	 * @param radius   Radius of the region considered in non-maximal suppression.
	 *                 Typical values to use might be 1-3 pixels.
	 * @param threshold
	 * @param row row coordinates of corner points
	 * @param column column coordinates
	 * @param rsubp  Sub-pixel localization of feature points is attempted and returned as as 
	 *               additional set of floating point coordinates.  Note that you may still want
	 *               to use the integer valued coordinates to specify centers of correlation
	 *               windows for feature matching.
	 * @param csubp
	 */
	public AlgorithmNonMaxSuppts(ModelImage destImg, ModelImage srcImg, int radius, double threshold,
			                     int[] row, int[] column, double[] rsubp, double[] csubp) {
		super(destImg, srcImg);	
		this.radius = radius;
		this.threshold = threshold;
		this.row = row;
		this.column = column;
		this.rsubp = rsubp;
		this.csubp = csubp;
	}

	 /**
     * finalize -
     */
    public void finalize() {
        super.finalize();
    }

    /**
     * Starts the program.
     */
    public void runAlgorithm() {
    	
    }
}